#!/usr/bin/env python3
"""paper3_latex_table.py — Generate publication-ready LaTeX Table 1 for Paper 3.

Reads gamma_fit_results.csv and produces a formatted LaTeX table suitable
for direct inclusion in the paper.

Usage:
    python3 paper3_latex_table.py [--input gamma_fit_results.csv] [--output paper3_draft_table1.tex]

License: MIT
"""

import argparse
import csv
import os
import sys


def main():
    parser = argparse.ArgumentParser(
        description="Generate LaTeX Table 1 from gamma fit results.")
    parser.add_argument("--input", type=str, default="gamma_fit_results.csv",
                        help="Input CSV with gamma fit data")
    parser.add_argument("--output", type=str, default="paper3_draft_table1.tex",
                        help="Output .tex file")
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"ERROR: {args.input} not found. Run paper3_area_decay.py first.")
        sys.exit(1)

    with open(args.input, "r") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    # ── Build LaTeX ──────────────────────────────────────────────────────────
    latex = []
    latex.append(r"% Paper 3 — Table 1: Universal Fragility Exponents")
    latex.append(r"% Auto-generated by paper3_latex_table.py")
    latex.append(r"\begin{table}[htbp]")
    latex.append(r"  \centering")
    latex.append(r"  \caption{Fitted fragility exponent $\gamma$ for each test function $g(y)$.")
    latex.append(r"    The iteration $z_{n+1} = K \cdot z_n \cdot g(\operatorname{Im}(z_n)) + c$")
    latex.append(r"    yields area decay $A(K) \sim C \cdot K^{-\gamma}$.")
    latex.append(r"    Predicted exponents follow from Theorem~4.2:")
    latex.append(r"    $\gamma = 2$ for Class~A ($g(0) > 0$),")
    latex.append(r"    $\gamma = 2/(1+\alpha)$ for power-law vanishing of order $\alpha$,")
    latex.append(r"    $\gamma = 1$ for Class~B (tanh).}")
    latex.append(r"  \label{tab:gamma-exponents}")
    latex.append(r"  \begin{tabular}{llccccl}")
    latex.append(r"    \toprule")
    latex.append(r"    $g(y)$ & Class & $\gamma_{\text{pred}}$ & $\gamma_{\text{fit}}$ & Error\,(\%) & $R^2$ & Note \\")
    latex.append(r"    \midrule")

    class_map = {
        "power_alpha_0.5":  ("$|y|^{1/2}$",  "A$^*$", "Vanishing order $\\alpha = 1/2$"),
        "power_alpha_0.75": ("$|y|^{3/4}$",  "A$^*$", "Vanishing order $\\alpha = 3/4$"),
        "power_alpha_1.0":  ("$|y|$",         "B",     "Equivalent to $\\alpha = 1$"),
        "power_alpha_2.0":  ("$|y|^2$",       "A$^*$", "Vanishing order $\\alpha = 2$"),
        "exp_neg_abs":      ("$e^{-|y|}$",    "A",     "$g(0) = 1 > 0$"),
        "tanh_abs":         ("$\\tanh(|y|)$", "B",     "$g'(0) = 1$, linear vanishing"),
        "sigmoid_abs":      ("$\\sigma(|y|)$","A",     "$g(0) = 1/2 > 0$"),
    }

    for row in rows:
        g_name = row["g_name"]
        g_tex, cls, note = class_map.get(g_name, (row["g_label"], "?", ""))

        gamma_pred = row["gamma_predicted"]
        gamma_fit = row["gamma_fit"]
        pct_err = row["pct_error"]
        r_sq = row["r_squared"]

        if gamma_fit and gamma_fit != "None":
            gamma_pred_f = f"{float(gamma_pred):.4f}"
            gamma_fit_f = f"{float(gamma_fit):.4f}"
            pct_err_f = f"{float(pct_err):.1f}" if pct_err and pct_err != "None" else "--"
            r_sq_f = f"{float(r_sq):.4f}" if r_sq and r_sq != "None" else "--"
        else:
            gamma_pred_f = f"{float(gamma_pred):.4f}" if gamma_pred and gamma_pred != "None" else "--"
            gamma_fit_f = "--"
            pct_err_f = "--"
            r_sq_f = "--"

        latex.append(
            f"    {g_tex} & {cls} & {gamma_pred_f} & {gamma_fit_f} "
            f"& {pct_err_f} & {r_sq_f} & {note} \\\\"
        )

    latex.append(r"    \bottomrule")
    latex.append(r"  \end{tabular}")
    latex.append(r"  \vspace{0.3em}")
    latex.append(r"  \begin{minipage}{0.9\textwidth}")
    latex.append(r"    \footnotesize")
    latex.append(r"    $^*$Class~A$^*$ denotes power-law functions that vanish at $y = 0$;")
    latex.append(r"    they follow the modified exponent $\gamma = 2/(1+\alpha)$ rather than")
    latex.append(r"    the Class~A universal $\gamma = 2$.")
    latex.append(r"  \end{minipage}")
    latex.append(r"\end{table}")

    tex_content = "\n".join(latex)

    with open(args.output, "w") as f:
        f.write(tex_content)

    print(f"=== Paper 3 LaTeX Table 1 ===")
    print(f"  Input:  {args.input}")
    print(f"  Output: {args.output}")
    print()
    print(tex_content)
    print(f"\n=== Done ===")


if __name__ == "__main__":
    main()
